# Generated by Django 5.0 on 2023-12-27 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jogador', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jogador',
            name='cor',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='jogador',
            name='nome',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
