# Generated by Django 5.0 on 2023-12-29 16:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jogador', '0003_carta_pais_jogador_cartas_jogador_paises_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pais',
            name='jogador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paises_jogador', to='jogador.jogador'),
        ),
        migrations.AlterField(
            model_name='jogador',
            name='paises',
            field=models.ManyToManyField(related_name='jogadores', to='jogador.pais'),
        ),
    ]
