# Generated by Django 5.0 on 2023-12-30 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jogador', '0004_pais_jogador_alter_jogador_paises'),
    ]

    operations = [
        migrations.AddField(
            model_name='jogador',
            name='distribuindo_tropas',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='jogador',
            name='tropas_distribuir',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
