# Generated by Django 5.0 on 2023-12-30 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jogador', '0005_jogador_distribuindo_tropas_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pais',
            name='nome',
            field=models.CharField(max_length=255),
        ),
    ]
